CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(120) NOT NULL,
    isbn VARCHAR(17) NOT NULL,
    CONSTRAINT uq_books_isbn UNIQUE (isbn),
    CONSTRAINT ck_books_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT ck_books_author_not_blank CHECK (btrim(author) <> ''),
    CONSTRAINT ck_books_isbn_length CHECK (char_length(isbn) BETWEEN 10 AND 17)
);

CREATE TABLE roles (
    name VARCHAR(40) PRIMARY KEY,
    description VARCHAR(200) NOT NULL,
    CONSTRAINT ck_roles_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_name VARCHAR(40) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_name),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_name) REFERENCES roles (name) ON DELETE RESTRICT
);

INSERT INTO roles (name, description) VALUES
    ('member', 'Retira livros e consulta o próprio histórico.'),
    ('librarian', 'Administra acervo, usuários e devoluções.');

INSERT INTO user_roles (user_id, role_name)
    SELECT id, 'member' FROM users;

CREATE TABLE external_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    issuer VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_external_identities_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_external_identities_issuer_subject UNIQUE (issuer, subject),
    CONSTRAINT ck_external_identities_issuer_not_blank CHECK (btrim(issuer) <> ''),
    CONSTRAINT ck_external_identities_subject_not_blank CHECK (btrim(subject) <> '')
);

CREATE INDEX ix_external_identities_user_id
    ON external_identities (user_id);

CREATE TABLE oidc_login_attempts (
    id UUID PRIMARY KEY,
    issuer VARCHAR(255) NOT NULL,
    browser_digest VARCHAR(64) NOT NULL,
    state_digest VARCHAR(64) NOT NULL,
    nonce_digest VARCHAR(64) NOT NULL,
    verifier_digest VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    CONSTRAINT uq_oidc_login_attempts_browser_digest UNIQUE (browser_digest),
    CONSTRAINT uq_oidc_login_attempts_state_digest UNIQUE (state_digest),
    CONSTRAINT ck_oidc_login_attempts_expiration_after_creation
        CHECK (expires_at > created_at),
    CONSTRAINT ck_oidc_login_attempts_used_after_creation
        CHECK (used_at IS NULL OR used_at >= created_at)
);

CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    borrowed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ,
    CONSTRAINT fk_loans_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_loans_book FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE RESTRICT,
    CONSTRAINT ck_loans_due_after_borrowed CHECK (due_at > borrowed_at),
    CONSTRAINT ck_loans_returned_after_borrowed CHECK (
        returned_at IS NULL OR returned_at >= borrowed_at
    )
);

CREATE UNIQUE INDEX uq_loans_one_active_per_book
    ON loans (book_id)
    WHERE returned_at IS NULL;

CREATE TABLE refresh_tokens (
    id UUID PRIMARY KEY,
    family_id UUID NOT NULL,
    user_id BIGINT NOT NULL,
    token_digest VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    replaced_by_id UUID,
    CONSTRAINT uq_refresh_tokens_token_digest UNIQUE (token_digest),
    CONSTRAINT uq_refresh_tokens_replaced_by_id UNIQUE (replaced_by_id),
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_refresh_tokens_replacement
        FOREIGN KEY (replaced_by_id) REFERENCES refresh_tokens (id) ON DELETE RESTRICT,
    CONSTRAINT ck_refresh_tokens_expiration_after_creation
        CHECK (expires_at > created_at),
    CONSTRAINT ck_refresh_tokens_used_after_creation
        CHECK (used_at IS NULL OR used_at >= created_at),
    CONSTRAINT ck_refresh_tokens_revoked_after_creation
        CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX ix_refresh_tokens_family_id ON refresh_tokens (family_id);
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE api_clients (
    id UUID PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_api_clients_name UNIQUE (name),
    CONSTRAINT ck_api_clients_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE api_keys (
    id UUID PRIMARY KEY,
    client_id UUID NOT NULL,
    prefix VARCHAR(12) NOT NULL,
    secret_digest VARCHAR(64) NOT NULL,
    scopes JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    replaced_by_id UUID,
    CONSTRAINT fk_api_keys_client
        FOREIGN KEY (client_id) REFERENCES api_clients (id) ON DELETE CASCADE,
    CONSTRAINT fk_api_keys_replacement
        FOREIGN KEY (replaced_by_id) REFERENCES api_keys (id) ON DELETE RESTRICT,
    CONSTRAINT uq_api_keys_prefix UNIQUE (prefix),
    CONSTRAINT uq_api_keys_replaced_by_id UNIQUE (replaced_by_id),
    CONSTRAINT ck_api_keys_prefix_length CHECK (char_length(prefix) = 12),
    CONSTRAINT ck_api_keys_digest_length CHECK (char_length(secret_digest) = 64),
    CONSTRAINT ck_api_keys_expiration_after_creation
        CHECK (expires_at IS NULL OR expires_at > created_at),
    CONSTRAINT ck_api_keys_revoked_after_creation
        CHECK (revoked_at IS NULL OR revoked_at >= created_at),
    CONSTRAINT ck_api_keys_last_use_after_creation
        CHECK (last_used_at IS NULL OR last_used_at >= created_at)
);

CREATE INDEX ix_api_keys_client_id ON api_keys (client_id);
