from datetime import UTC, datetime, timedelta

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from app.models import Base, Book, Loan, User


def postgres_ddl(table: type[Base]) -> str:
    return str(
        CreateTable(table.__table__).compile(dialect=postgresql.dialect())
    ).lower()


def test_metadata_matches_the_three_designed_entities() -> None:
    assert set(Base.metadata.tables) == {"users", "books", "loans"}
    assert "available" not in Book.__table__.columns
    assert User.__table__.columns["email"].type.length == 254
    assert User.__table__.columns["password_hash"].type.length == 255
    assert User.__table__.columns["password_hash"].nullable is True
    assert Book.__table__.columns["isbn"].type.length == 17


def test_postgresql_ddl_preserves_keys_and_temporal_constraints() -> None:
    users = postgres_ddl(User)
    books = postgres_ddl(Book)
    loans = postgres_ddl(Loan)

    assert "generated by default as identity" in users
    assert "constraint uq_users_email unique (email)" in users
    assert "constraint uq_books_isbn unique (isbn)" in books
    assert "constraint fk_loans_user foreign key(user_id)" in loans
    assert "references users (id) on delete restrict" in loans
    assert "constraint fk_loans_book foreign key(book_id)" in loans
    assert "timestamp with time zone" in loans
    assert "check (due_at > borrowed_at)" in loans


def test_partial_index_allows_only_one_active_loan_per_book() -> None:
    index = next(
        item
        for item in Loan.__table__.indexes
        if item.name == "uq_loans_one_active_per_book"
    )
    ddl = str(
        CreateIndex(index).compile(dialect=postgresql.dialect())
    ).lower()

    assert ddl == (
        "create unique index uq_loans_one_active_per_book "
        "on loans (book_id) where returned_at is null"
    )


def test_loan_is_an_association_object_with_bidirectional_relationships() -> None:
    now = datetime.now(UTC)
    user = User(name="Ada Lovelace", email="ada@example.com")
    book = Book(title="Kindred", author="Octavia E. Butler", isbn="9780807083697")
    loan = Loan(user=user, book=book, due_at=now + timedelta(days=14))

    assert loan.user is user
    assert loan.book is book
    assert user.loans == [loan]
    assert book.loans == [loan]
    assert User.loans.property.back_populates == "user"
    assert Book.loans.property.back_populates == "book"
    assert User.loans.property.passive_deletes is True
    assert Book.loans.property.passive_deletes is True
    assert User.loans.property.lazy == "raise"
    assert [column.name for column in User.loans.property.order_by] == ["id"]
    assert Book.loans.property.lazy == "raise"
    assert Loan.user.property.lazy == "raise"
    assert Loan.book.property.lazy == "raise"
