from datetime import UTC, datetime, timedelta

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from app.models import (
    Base,
    Book,
    ExternalIdentity,
    Loan,
    OidcLoginAttempt,
    RefreshToken,
    Role,
    User,
    UserRole,
)


def postgres_ddl(table: type[Base]) -> str:
    return str(
        CreateTable(table.__table__).compile(dialect=postgresql.dialect())
    ).lower()


def test_metadata_matches_the_eight_designed_entities() -> None:
    assert set(Base.metadata.tables) == {
        "users",
        "books",
        "loans",
        "refresh_tokens",
        "roles",
        "user_roles",
        "external_identities",
        "oidc_login_attempts",
    }
    assert "available" not in Book.__table__.columns
    assert User.__table__.columns["email"].type.length == 254
    assert User.__table__.columns["password_hash"].type.length == 255
    assert User.__table__.columns["password_hash"].nullable is True
    assert Book.__table__.columns["isbn"].type.length == 17
    assert RefreshToken.__table__.columns["token_digest"].type.length == 64
    assert Role.__table__.columns["name"].type.length == 40


def test_postgresql_ddl_preserves_keys_and_temporal_constraints() -> None:
    users = postgres_ddl(User)
    books = postgres_ddl(Book)
    loans = postgres_ddl(Loan)

    assert "generated by default as identity" in users
    assert "constraint uq_users_email unique (email)" in users
    assert "constraint uq_books_isbn unique (isbn)" in books
    assert "constraint fk_loans_user foreign key(user_id)" in loans
    assert "references users (id) on delete restrict" in loans
    assert "constraint fk_loans_book foreign key(book_id)" in loans
    assert "timestamp with time zone" in loans
    assert "check (due_at > borrowed_at)" in loans


def test_partial_index_allows_only_one_active_loan_per_book() -> None:
    index = next(
        item
        for item in Loan.__table__.indexes
        if item.name == "uq_loans_one_active_per_book"
    )
    ddl = str(
        CreateIndex(index).compile(dialect=postgresql.dialect())
    ).lower()

    assert ddl == (
        "create unique index uq_loans_one_active_per_book "
        "on loans (book_id) where returned_at is null"
    )


def test_refresh_tokens_preserve_digest_family_and_replacement_chain() -> None:
    ddl = postgres_ddl(RefreshToken)

    assert "token_digest varchar(64) not null" in ddl
    assert "constraint uq_refresh_tokens_token_digest unique (token_digest)" in ddl
    assert "constraint fk_refresh_tokens_user foreign key(user_id)" in ddl
    assert "constraint fk_refresh_tokens_replacement foreign key(replaced_by_id)" in ddl
    assert "check (expires_at > created_at)" in ddl
    assert {index.name for index in RefreshToken.__table__.indexes} == {
        "ix_refresh_tokens_family_id",
        "ix_refresh_tokens_user_id",
    }


def test_loan_is_an_association_object_with_bidirectional_relationships() -> None:
    now = datetime.now(UTC)
    user = User(name="Ada Lovelace", email="ada@example.com")
    book = Book(title="Kindred", author="Octavia E. Butler", isbn="9780807083697")
    loan = Loan(user=user, book=book, due_at=now + timedelta(days=14))

    assert loan.user is user
    assert loan.book is book
    assert user.loans == [loan]
    assert book.loans == [loan]
    assert User.loans.property.back_populates == "user"
    assert Book.loans.property.back_populates == "book"
    assert User.loans.property.passive_deletes is True
    assert Book.loans.property.passive_deletes is True
    assert User.loans.property.lazy == "raise"
    assert [column.name for column in User.loans.property.order_by] == ["id"]
    assert Book.loans.property.lazy == "raise"
    assert Loan.user.property.lazy == "raise"
    assert Loan.book.property.lazy == "raise"


def test_roles_form_an_explicit_many_to_many_assignment() -> None:
    user = User(name="Ada Lovelace", email="ada@example.com")
    assignment = UserRole(role_name="member", user=user)
    role = Role(name="member", description="Pessoa leitora")
    assignment.role = role

    assert assignment in user.role_assignments
    assert assignment in role.user_assignments
    assert list(UserRole.__table__.primary_key.columns.keys()) == [
        "user_id",
        "role_name",
    ]
    assert User.role_assignments.property.lazy == "raise"
    assert Role.user_assignments.property.lazy == "raise"


def test_external_identity_uses_stable_issuer_and_subject() -> None:
    ddl = postgres_ddl(ExternalIdentity)

    assert "issuer varchar(255) not null" in ddl
    assert "subject varchar(255) not null" in ddl
    assert "constraint uq_external_identities_issuer_subject unique (issuer, subject)" in ddl
    assert "references users (id) on delete cascade" in ddl
    assert User.external_identities.property.lazy == "raise"


def test_oidc_attempt_persists_only_digests_and_one_time_state() -> None:
    ddl = postgres_ddl(OidcLoginAttempt)

    assert "browser_digest varchar(64) not null" in ddl
    assert "state_digest varchar(64) not null" in ddl
    assert "nonce_digest varchar(64) not null" in ddl
    assert "verifier_digest varchar(64) not null" in ddl
    assert "check (expires_at > created_at)" in ddl
    assert "state " not in ddl
    assert "code_verifier" not in ddl
